#
# Fichier configuration du practice par Edmine Network.
# Dev: EdmineCoreTeam
# Version: 0.1
#

Lobby:
  world: 'none'
  x: 0.0
  y: 0.0
  z: 0.0
  t: 0.0
  b: 0.0

KitEditor:
  world: 'none'
  x: 0.0
  y: 0.0
  z: 0.0
  t: 0.0
  b: 0.0

kits:
  unranked:
    nodebuff:
      name: '&d&lNodebuff'
      id: 'nodebuff'
      type: 'normal'
      icon: 'potion'
      potionid: '16421'
      content:
        helmet:
          item: 'diamond_helmet'
          isenchant: 'yes'
          enchants:
            - ''
            - ''